Commented out line that was causing:
qgis/src/providers/postgres/qgspostgresprovider.cpp:920: error: ‘mTables’ was not declared in this scope

Please fix and re-enable as needed



git-svn-id: http://svn.osgeo.org/qgis@7665 c8812cc2-4d05-0410-92ff-de0c093fc19c